### ISSUE TITLE
change activate into on/off, and add more scripts on 1 line

### ISSUE THREAD

**Issue by hvbhome** [tringler/hass-custom-ui_scenes#1]
followup from: https://github.com/andrey-git/home-assistant-custom-ui/issues/118#issuecomment-370181937

thank you,

what i don't understand: i did state your custom card didnt I?

i fail to see the error im this code, compared to what you put in your repo here:

```
homeassistant:
  customize:
    group.iungo_force_switches:
      custom_ui_state_card: state-card-custom_scene
      config:
        entities:
          - entity: script.sw_audio_auditorium_force_off
            friendly_name: Audio Auditorium
            icon: mdi:speaker
            state: binary_sensor.audio_auditorium
            templates:
              state: return 'Off';
          - entity: script.sw_audio_auditorium_force_on
            friendly_name: Audio Auditorium
            icon: mdi:speaker
            state: binary_sensor.audio_auditorium
            templates:
              state: return 'On';

```

also, i did try the templates under the custom-ui but that didn't work either...

fwiw: i have custom-ui loaded globally in customize_glob.yaml for *.*

Would that create a conflict in any way?

Thanks,
Marius

**Comment by tringler** [comment]
No - I have the same config.
Please remove:
```
            templates:
              state: return 'On';
```

**Comment by hvbhome** [comment]
a now i see... duh..

like this you mean:

```
group.iungo_force_switches:
  custom_ui_state_card: state-card-custom_scene
  config:
    entities:
      - entity: script.sw_audio_auditorium_force_off
        friendly_name: Audio Auditorium  #define icon and friendly_name or both
        icon: mdi:speaker #define icon and friendly_name or both
        state: binary_sensor.audio_auditorium # the binary sensor to determine the current state
        
      - entity: script.sw_audio_auditorium_force_on
        friendly_name: Audio Auditorium  #define icon and friendly_name or both
        icon: mdi:speaker #define icon and friendly_name or both
        state: binary_sensor.audio_auditorium # the binary sensor to determine the current state


      - entity: script.sw_tv_auditorium_force_off
        friendly_name: Tv Auditorium  #define icon and friendly_name or both
        icon: mdi:television #define icon and friendly_name or both
        state: binary_sensor.tv_auditorium # the binary sensor to determine the current state

      - entity: script.sw_tv_auditorium_force_on
        friendly_name: Tv Auditorium  #define icon and friendly_name or both
        icon: mdi:television #define icon and friendly_name or both
        state: binary_sensor.tv_auditorium # the binary sensor to determine the current state

```

How do i get these grouped per device on 1 line then? 

Tv Auditorium    On   Off   State
Audio Auditorium On Off State

etc etc

**Comment by tringler** [comment]
With that config you will get `On` and `Off` in one line and that one which is currently `On` (or playing) will highlighted in blue.

**Comment by hvbhome** [comment]
still struggling...

HA complains about double entries for icon and friendly_name.
When i create these as new groups, i get an error about the friendly_name not being valid for Group...

oiw:

what is the basic architecture, knowing i have custom-ui loaded globally and have a current group, with separate entries for each script(calling a command)...

**Comment by tringler** [comment]
Strange - That is exactly how I do it:
```
group.livingroom_harmony:
  friendly_name: Harmony
  icon: mdi:television
  custom_ui_state_card: state-card-custom_scene
  config:
    entities:
      - entity: script.remote_livingroom_harmony_entertain
        friendly_name: TV
        state: binary_sensor.harmony_entertain
      - entity: script.remote_livingroom_harmony_ps4
        friendly_name: PS4
        state: binary_sensor.harmony_ps4
      - entity: script.remote_livingroom_harmony_firetv
        friendly_name: FTV
        state: binary_sensor.harmony_firetv
      - entity: script.remote_livingroom_harmony_music
        friendly_name: Music
        state: binary_sensor.harmony_music
      - entity: script.remote_livingroom_harmony_turn_off
        friendly_name: Power Off
        state: binary_sensor.dummy_always_off
```

Can you post the error HA gave you about the double entries?

**Comment by hvbhome** [comment]
will reset the file quickly to do that.

but just to be sure:

your harmony configuration is the homeassistant: customize , or the group setup in homeassistant: group?

if it is in customize, do you have the group.livingroom_harmony already setup in the group section, and yes, how, or is this the full setup for this group?

**Comment by tringler** [comment]
It's in the `customize` section. Do you use Chrome or FireFox?

This is my group config:
```
livingroom:
  name: Wohnzimmer
  view: no
  entities:   
    - binary_sensor.livingroom_climate_windowshutter  
    - sensor.livingroom_climate_humidity
    - sensor.livingroom_climate_temperature
    - climate.livingroom_thermostat
    - binary_sensor.flower_kitchen_healthy
    - light.livingroom_ceilinglight
    - group.livingroom_harmony
    - group.livingroom_scenes
    - input_text.livingroom_music_dummy
    - input_text.livingroom_firetv_dummy
    - input_text.livingroom_ps4_dummy

livingroom_harmony:
  view: no
  entities:
    - script.remote_livingroom_harmony_tv
    - script.remote_livingroom_harmony_firetv
    - script.remote_livingroom_harmony_ps4
    - script.remote_livingroom_harmony_music
```

**Comment by hvbhome** [comment]
Thanks! making progress... finally. not quite there yet but we have something to build from:


![schermafbeelding 2018-03-05 om 22 49 55](https://user-images.githubusercontent.com/33354141/37001687-9c2252ae-20c7-11e8-83ac-48787e266624.jpg)


so the way to go is:

1-  create group for a device in HA group section, with set of commands per this device
2- (optional for grouping together all groups under 1) create a group with these groups, but hide them
3- customize these individual groups in HA Customize section, with commands per device, so they show up on 1 line in the group....

note1: if already using custom-ui use https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/features.md#secondary-customui secondary-customui

`state_card_custom_ui_secondary: state-card-custom_scene`
 
instead of regular 

`custom_ui_state_card: state-card-custom_scene`

see library, kantoor and gym which use regular expression, the others use secondary expression.

note2: no trailing s ;-) on `state-card-custom_scene`

**Comment by fanaticDavid** [comment]
Put the friendly_names `On` and `Off` between quotes. Otherwise, Home Assistant interprets them as booleans, hence the resulting TRUE.

**Comment by hvbhome** [comment]
thanks, rebooting ;-)
any thoughts why there's no Off, and  only On shows (in their boolean version)?

**Comment by hvbhome** [comment]
better indeed with the 'on' and 'off' in the config...

![schermafbeelding 2018-03-06 om 00 06 24](https://user-images.githubusercontent.com/33354141/37004921-66ddb5d8-20d2-11e8-9217-08012ca5cc18.jpg)

sensors light up both on and off though, needs further finetuning and research.

**Comment by tringler** [comment]
It is because you use the same binary sensor for `script.sw_tv_auditorium_force_off` and `script.sw_tv_auditorium_force_on` - You would need a binary sensors like `binary_sensor.sw_audio_auditorium_force_off_state` and `binary_sensor.sw_audio_auditorium_force_on_state`

**Comment by hvbhome** [comment]
ok i see
i was hoping the option `state:` would really read the state of a binary sensor... I guess it is too much to ask if this could be changed in a future version? It would really enhance the functionality enormously.

my use case is for 'forcing' several mqtt switches  that sometimes don't get their command sent through properly, which causes the state not to be read correctly, which causes the switch not to be switchable ...... I then need the just send the on or off command, and the switch is back in track again.

Thats why next to my regular switches i had my scripts calling these individual commands. Your scene-card could make it so much nicer on the eye as opposed to the long list of separate scripts i had before ;-)

Anyways, thanks a bunch, and hope you would be willing to consider making this possible.

other question: can we adapt the buttons in any way? next to the text, it would be nice change their appearance? No big deal, but could be a nice feature.

Cheers!
Marius

**Comment by tringler** [comment]
> i was hoping the option state: would really read the state of a binary sensor... I guess it is too much to ask if this could be changed in a future version? It would really enhance the functionality enormously.

I don't understand that, because it actually reads the sensor value to highlight or not highlight the text to show which script/scene is active.

It should not be a problem if you use REST commands. Can you check if you see some errors on the console from the developer tools? Do you have the same problem on Chrome and Firefox. I have also problems to display the card on Chrome at the moment.
To avoid caching problems you should try to delete the cache or you a incognito tab, where you don't use cached data.

> other question: can we adapt the buttons in any way? next to the text, it would be nice change their appearance? No big deal, but could be a nice feature.

You mean an option to style the buttons?

**Comment by hvbhome** [comment]
yes Chrome and Firefox show the same as Safari on Mac .

i was thinking of taking out the state: and maybe color the group name Audio Auditorium when on/active. That way i could see if the command actually took place, and the design thinking of your custom card would not have to be adapted?

In any case i can see a blue border around the button pressed, so that would be a sufficient indication together with the 'active' name.

On the style buttons: yes, now we have this large button, but maybe a small circle or something like that could be possible?

![schermafbeelding 2018-03-06 om 13 46 31](https://user-images.githubusercontent.com/33354141/37033101-04042b7c-2145-11e8-965a-4915ac999123.jpg)

btw this is the state in the dev tools, to show you it really is set correctly:

![schermafbeelding 2018-03-06 om 13 49 23](https://user-images.githubusercontent.com/33354141/37033152-3b3da3a2-2145-11e8-8415-3a40bbae7bb5.jpg)

**Comment by hvbhome** [comment]
fwiw, none of these work:

 ```
 templates:
   rgb_color: >
        {% if is_state("sensor.audio_auditorium_state", "on") %} [251, 210, 41]
        {% else %} [54, 95, 140]
        {%- endif %}

```

```
templates:
    rgb_color: >
      {% if states.sensor.tv_auditorium_state == "on" %} [251, 210, 41]
      {% else %} [54, 95, 140]
      {%- endif %}
```

```
  templates:
   theme: >
        {% if is_state("sensor.kantoor_state", "on") %} green
        {% else %} grey
        {%- endif %}
```

....

**Comment by tringler** [comment]
> i was thinking of taking out the state: and maybe color the group name Audio Auditorium when on/active. That way i could see if the command actually took place, and the design thinking of your custom card would not have to be adapted?

I don't understand. You mean I should declare state as optional and then with andreys custom-ui you will style the button or do you mean that my state-card should implement styling?

> In any case i can see a blue border around the button pressed, so that would be a sufficient indication together with the 'active' name.

It is expected, that both buttons are highlighted blue, because you are using the same state sensor for both scripts. The card is designed that you have different scripts with different state sensors, but I'm open to declare the the state parameter as optional and highlight all scripts in the current line.

I want to have it generic - I don't want to have hardcoded style elements. In example my scene cards are looking like:

![grafik](https://user-images.githubusercontent.com/4985268/37086950-3600a81c-21f9-11e8-95ca-ff801d7f356d.png)

In that case I don't like to have borders i it's not defined in the HASS theme.

> fwiw, none of these work:

These parameters are andreys custom-ui templates right? To be honest I don't have any idea why it's not working. Maybe because I have also state-card parameters and that's not supported. You should file a issue at andreys state card I guess.

**Comment by hvbhome** [comment]
> It

 is expected, that both buttons are highlighted blue, because you are using the same state sensor for both scripts. The card is designed that you have different scripts with different state sensors, but I'm open to declare the the state parameter as optional and highlight all scripts in the current line.< 

very nice to consider, thanks, but im not sure your suggestions fits this situation. I have scripts for on and off of the same entity on one line (and will add several others) these on and off states should be read, and not the state of the script.... I use the binary sensor that reads the state of the entity, not the script.

> These parameters are andreys custom-ui templates right? To be honest I don't have any idea why it's not working.<

could it be this is code for templating an single entity, and no the full  group. Cause thats what we need to do here?
in your card above: im trying to get the same result as with your Deckenlampe: it is on, so the icon should be lit.
In my example: if the switch is on the icon of the group should be lit, just like everywhere in HomeAssistant ;-)

Ill see if group templating is possible at all like this.

**Comment by tringler** [comment]
First of all: I just seen in your customization you are using `state: sensor.audio_auditorium_state` instead of `state: binary_sensor.audio_auditorium_state

> I have scripts for on and off of the same entity on one line (and will add several others) these on and off states should be read, and not the state of the script.... I use the binary sensor that reads the state of the entity, not the script.

Yes - and that sensor should be `binary_sensor.audio_auditorium_state` - A script has no state. The state card doesn't read the script state. It reads the sensor state of `state` and highlight or not highlight depending on the state of the sensor. It must be a binary_sensor or the state must be `on` or `off`.

> In my example: if the switch is on the icon of the group should be lit, just like everywhere in HomeAssistant ;-)

Ok. I will change that in the next version. If one the sensors in one lines reports `on` the group light will switched on.

**Comment by tringler** [comment]
By the way - Is your use-case not covered by https://home-assistant.io/components/switch.template/?

**Comment by hvbhome** [comment]
HI @tringler ,

thanks!
the sensor is a binary sensor, though not one in the category binary_sensor, but mqtt sensor reading State.

I have tried the regular binary_sensor too, and it has the same result.

will make another effort to see if recent changes in the setup make any difference on this aspect.

And about the switch.template: i use these heavily. As a matter of fact, it is my main setup, to read my zwave switches over mqtt (it is an external zwave hub), and switch these over command_line. My hub doesn't except mqtt published events, so i had to use command_line api instructions.

The issue is that every once in a while these switches don't correctly set their state, thus frustrating these switch.templates. I than need to manually force switch them on or off. Thats where these script come in, and thats why i would love to use your custom-scene card!

Hope you can achieve the coloring of the main icon on the line according to the actual On/Off state of the state sensor.

still cant display the third script, any thoughts? they are visible in the more info screen. Could it be it is it has no 'state' line? It is used for forcing the zwave sensor to read the state, and populate the appropriate field.

![schermafbeelding 2018-03-07 om 13 31 46](https://user-images.githubusercontent.com/33354141/37092449-3dc31f86-220c-11e8-9215-a479076563da.jpg)

![schermafbeelding 2018-03-07 om 13 31 36](https://user-images.githubusercontent.com/33354141/37092458-44aa3c80-220c-11e8-9968-f2a9d0aeeab3.jpg)

```
    group.iungo_force_t:
      friendly_name: Tester
      templates: 
        rgb_color: "if (states.sensor.tester_state.state === 'on')
                        return [251, 210, 41]; else return [54, 95, 140];"
      icon: mdi:test-tube
      state_card_custom_ui_secondary: state-card-custom_scene
      config:
        entities:
          - entity: script.tester_force_off
            friendly_name: 'Off'
            state: binary_sensor.tester
          - entity: script.tester_force_on
            friendly_name: 'On'
            state: binary_sensor.tester
          - entity: script.tester_state
            friendly_name: 'State'
```

**Comment by tringler** [comment]
> still cant display the third script, any thoughts? they are visible in the more info screen. Could it be it is it has no 'state' line? It is used for forcing the zwave sensor to read the state, and populate the appropriate field.

Correct.
As of now you can use a dummy template binary sensor like:
```
dummy_always_on:
  value_template: True
```
and put it on `state: binary_sensor.dummy_always_on:`

To summarize - Improvements for the next version
1) State is optional - If not specified it will highlght it (like every other script)
2) Group icon will be lit if one the states is `on`
3) Apply style to buttons

Right?

**Comment by hvbhome** [comment]
cool, magic!
hope you can make it, cause the javascript versus Jinja templating @andrey suggested doesn't seem t make any difference. I still suspect it to have to do with the fact that the icon represents a group, an not a device entity like normally.

Hope to be of assistance, let us know when your explorations are done!
Cheers,
M

**Comment by hvbhome** [comment]
ok, small succes:

this template does work. coloring the complete line according to the state and the defined template, provided you have a theme yellow and brown in the config:

```
      templates: 
        theme: "if (entities['sensor.tv_auditorium_state'].state === 'on')
                        return 'yellow'; else return 'brown';"

```
```
theme:
  yellow:
  primary-text-color: yellow
  paper-card-background-color: lightgrey
  paper-item-icon-color: yellow
  secondary-text-color: yellow
  label-badge-background-color: lightgrey
  label-badge-text-color: yellow
  label-badge-red: grey
  label-badge-border-color: yellow
```


no such luck yet with rob_color, but i will keep trying ;-)
